#!/usr/bin/env python3
from pathlib import Path
import csv
import json

ROOT = Path("/volume1/docker/nas-stack")
PROJECT_JSON = ROOT / "project" / "generated" / "project.json"
JIRA_KEYS_JSON = ROOT / "project" / "meta" / "jira_keys.json"
EXPORT_DIR = ROOT / "project" / "exports"

EPICS_CSV = EXPORT_DIR / "jira_epics.csv"
ISSUES_CSV = EXPORT_DIR / "jira_issues.csv"
NOTES_MD = EXPORT_DIR / "jira_import_notes.md"

EPIC_FIELDS = ["Summary", "Issue Type", "Status", "Description", "Labels"]
ISSUE_FIELDS = ["Summary", "Issue Type", "Status", "Description", "Labels", "Parent"]


def load_project():
    return json.loads(PROJECT_JSON.read_text(encoding="utf-8"))


def load_jira_keys():
    if not JIRA_KEYS_JSON.exists():
        return {"epics": {}, "stories": {}, "versions": {}, "components": {}}
    return json.loads(JIRA_KEYS_JSON.read_text(encoding="utf-8"))


def write_csv(path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def normalize_status(status):
    s = str(status).strip().lower()
    if s in ("done", "completed", "released", "closed"):
        return "Done"
    if s in ("active", "in progress", "in-progress"):
        return "In Progress"
    return "To Do"


def epic_rows(project):
    rows = []
    for epic in project.get("epics", []):
        rows.append({
            "Summary": epic.get("name", ""),
            "Issue Type": "Epic",
            "Status": normalize_status(epic.get("status", "")),
            "Description": (
                "Generated by CORE Project Intelligence Engine\n\n"
                f"Epic Key: {epic.get('key', '')}\n"
                f"Release: {epic.get('release', '')}\n"
                f"Sprint: {epic.get('sprint', '')}"
            ),
            "Labels": "core,generated,epic",
        })
    return rows


def issue_rows(project, jira_keys):
    rows = []
    epic_map = jira_keys.get("epics", {})

    for feature in project.get("features", []):
        core_epic_key = feature.get("epic", "")
        jira_parent = epic_map.get(core_epic_key, core_epic_key)

        rows.append({
            "Summary": feature.get("name", ""),
            "Issue Type": "Story",
            "Status": normalize_status(feature.get("status", "")),
            "Description": (
                "Generated by CORE Project Intelligence Engine\n\n"
                f"Feature Key: {feature.get('key', '')}\n"
                f"CORE Epic: {core_epic_key}\n"
                f"Jira Parent: {jira_parent}"
            ),
            "Labels": "core,generated,feature",
            "Parent": jira_parent,
        })

    for issue in project.get("issues", []):
        rows.append({
            "Summary": issue.get("summary", issue.get("key", "")),
            "Issue Type": issue.get("type", "Story"),
            "Status": normalize_status(issue.get("status", "")),
            "Description": (
                "Generated from historical CORE Markdown issue\n\n"
                f"Issue Key: {issue.get('key', '')}\n"
                f"File: {issue.get('file', '')}\n\n"
                f"{issue.get('description', '')}"
            ),
            "Labels": issue.get("labels", "core,historical") or "core,historical",
            "Parent": "",
        })

    return rows


def write_notes():
    NOTES_MD.write_text("""# Jira Import Notes

Import order:
1. jira_epics.csv
2. jira_issues.csv

Mapping epics:
- Summary -> Samenvatting
- Issue Type -> Type issue
- Status -> Status
- Description -> Beschrijving
- Labels -> Labels

Mapping stories:
- Summary -> Samenvatting
- Issue Type -> Type issue
- Status -> Status
- Description -> Beschrijving
- Labels -> Labels
- Parent -> Bovenliggend item / Parent

Parent mapping gebruikt project/meta/jira_keys.json.
Historische issues hebben voorlopig geen Parent.
""", encoding="utf-8")


def main():
    if not PROJECT_JSON.exists():
        raise FileNotFoundError("project.json ontbreekt. Run eerst ./genproject")

    project = load_project()
    jira_keys = load_jira_keys()

    write_csv(EPICS_CSV, EPIC_FIELDS, epic_rows(project))
    write_csv(ISSUES_CSV, ISSUE_FIELDS, issue_rows(project, jira_keys))
    write_notes()

    print("Jira Free export klaar.")
    print(f"- {EPICS_CSV}")
    print(f"- {ISSUES_CSV}")
    print(f"- {NOTES_MD}")


if __name__ == "__main__":
    main()
