FROM python:3.13-alpine
WORKDIR /app
RUN pip install --no-cache-dir psycopg2-binary==2.9.10 redis==6.2.0
COPY core ./core
COPY controlled_execution_worker.py ./controlled_execution_worker.py
CMD ["python", "controlled_execution_worker.py"]
