BEGIN;
SET LOCAL lock_timeout = '10s';

CREATE TABLE public.ai_output (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id integer,
    summary text,
    tags text[],
    categories text[],
    embedding public.vector(1536),
    created_at timestamptz DEFAULT now(),
    CONSTRAINT ai_output_file_id_fkey
        FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE
);

CREATE TABLE public.embeddings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id integer NOT NULL,
    embedding public.vector(1536),
    created_at timestamptz DEFAULT now(),
    CONSTRAINT embeddings_file_id_fkey
        FOREIGN KEY (file_id) REFERENCES public.files(id) ON DELETE CASCADE
);

CREATE OR REPLACE PROCEDURE public.cleanup_all_execute()
LANGUAGE plpgsql
AS $$
DECLARE
    dir_folders integer := 0;
    dir_files integer := 0;
    dir_meta integer := 0;
    dir_emb integer := 0;
    dir_ai integer := 0;
    file_files integer := 0;
    file_meta integer := 0;
    file_emb integer := 0;
    file_ai integer := 0;
    orphan_metadata integer := 0;
    orphan_embeddings integer := 0;
    orphan_ai integer := 0;
    orphan_files integer := 0;
    orphan_folders integer := 0;
BEGIN
    RAISE NOTICE '=== CLEANUP START ===';

    WITH excluded_folders AS (
        SELECT id FROM folders
        WHERE path LIKE '%/@eaDir%' OR path LIKE '%/@appstore%'
           OR path LIKE '%/@tmp%' OR path LIKE '%/@%'
    ), files_to_delete AS (
        SELECT id AS file_id FROM files
        WHERE folder_id IN (SELECT id FROM excluded_folders)
    )
    SELECT (SELECT count(*) FROM excluded_folders),
           (SELECT count(*) FROM files_to_delete),
           (SELECT count(*) FROM metadata WHERE file_id IN (SELECT file_id FROM files_to_delete)),
           (SELECT count(*) FROM embeddings WHERE file_id IN (SELECT file_id FROM files_to_delete)),
           (SELECT count(*) FROM ai_output WHERE file_id IN (SELECT file_id FROM files_to_delete))
    INTO dir_folders, dir_files, dir_meta, dir_emb, dir_ai;

    RAISE NOTICE 'DIRS: removing % folders, % files, % metadata, % embeddings, % ai_output',
        dir_folders, dir_files, dir_meta, dir_emb, dir_ai;

    DELETE FROM metadata WHERE file_id IN (SELECT id FROM files WHERE folder_id IN (
        SELECT id FROM folders WHERE path LIKE '%/@eaDir%' OR path LIKE '%/@appstore%'
            OR path LIKE '%/@tmp%' OR path LIKE '%/@%'));
    DELETE FROM embeddings WHERE file_id IN (SELECT id FROM files WHERE folder_id IN (
        SELECT id FROM folders WHERE path LIKE '%/@eaDir%' OR path LIKE '%/@appstore%'
            OR path LIKE '%/@tmp%' OR path LIKE '%/@%'));
    DELETE FROM ai_output WHERE file_id IN (SELECT id FROM files WHERE folder_id IN (
        SELECT id FROM folders WHERE path LIKE '%/@eaDir%' OR path LIKE '%/@appstore%'
            OR path LIKE '%/@tmp%' OR path LIKE '%/@%'));
    DELETE FROM files WHERE folder_id IN (SELECT id FROM folders
        WHERE path LIKE '%/@eaDir%' OR path LIKE '%/@appstore%'
           OR path LIKE '%/@tmp%' OR path LIKE '%/@%');
    DELETE FROM folders WHERE path LIKE '%/@eaDir%' OR path LIKE '%/@appstore%'
        OR path LIKE '%/@tmp%' OR path LIKE '%/@%';

    WITH excluded_files AS (
        SELECT id AS file_id FROM files
        WHERE filename LIKE '~$%' OR filename LIKE '._%'
           OR filename = '.DS_Store' OR filename = 'Thumbs.db'
           OR filename LIKE '%.tmp' OR filename LIKE '%.swp' OR filename LIKE '%.bak'
    )
    SELECT (SELECT count(*) FROM excluded_files),
           (SELECT count(*) FROM metadata WHERE file_id IN (SELECT file_id FROM excluded_files)),
           (SELECT count(*) FROM embeddings WHERE file_id IN (SELECT file_id FROM excluded_files)),
           (SELECT count(*) FROM ai_output WHERE file_id IN (SELECT file_id FROM excluded_files))
    INTO file_files, file_meta, file_emb, file_ai;

    RAISE NOTICE 'FILES: removing % files, % metadata, % embeddings, % ai_output',
        file_files, file_meta, file_emb, file_ai;

    DELETE FROM metadata WHERE file_id IN (SELECT id FROM files WHERE filename LIKE '~$%'
        OR filename LIKE '._%' OR filename = '.DS_Store' OR filename = 'Thumbs.db'
        OR filename LIKE '%.tmp' OR filename LIKE '%.swp' OR filename LIKE '%.bak');
    DELETE FROM embeddings WHERE file_id IN (SELECT id FROM files WHERE filename LIKE '~$%'
        OR filename LIKE '._%' OR filename = '.DS_Store' OR filename = 'Thumbs.db'
        OR filename LIKE '%.tmp' OR filename LIKE '%.swp' OR filename LIKE '%.bak');
    DELETE FROM ai_output WHERE file_id IN (SELECT id FROM files WHERE filename LIKE '~$%'
        OR filename LIKE '._%' OR filename = '.DS_Store' OR filename = 'Thumbs.db'
        OR filename LIKE '%.tmp' OR filename LIKE '%.swp' OR filename LIKE '%.bak');
    DELETE FROM files WHERE filename LIKE '~$%' OR filename LIKE '._%'
        OR filename = '.DS_Store' OR filename = 'Thumbs.db'
        OR filename LIKE '%.tmp' OR filename LIKE '%.swp' OR filename LIKE '%.bak';

    SELECT count(*) INTO orphan_metadata FROM metadata m LEFT JOIN files f ON f.id=m.file_id WHERE f.id IS NULL;
    DELETE FROM metadata m WHERE NOT EXISTS (SELECT 1 FROM files f WHERE f.id=m.file_id);
    SELECT count(*) INTO orphan_embeddings FROM embeddings e LEFT JOIN files f ON f.id=e.file_id WHERE f.id IS NULL;
    DELETE FROM embeddings e WHERE NOT EXISTS (SELECT 1 FROM files f WHERE f.id=e.file_id);
    SELECT count(*) INTO orphan_ai FROM ai_output a LEFT JOIN files f ON f.id=a.file_id WHERE f.id IS NULL;
    DELETE FROM ai_output a WHERE NOT EXISTS (SELECT 1 FROM files f WHERE f.id=a.file_id);
    SELECT count(*) INTO orphan_files FROM files fl LEFT JOIN folders fo ON fo.id=fl.folder_id WHERE fo.id IS NULL;
    DELETE FROM files fl WHERE NOT EXISTS (SELECT 1 FROM folders fo WHERE fo.id=fl.folder_id);
    SELECT count(*) INTO orphan_folders FROM folders f LEFT JOIN folders p ON p.id=f.parent_id
        WHERE f.parent_id IS NOT NULL AND p.id IS NULL;
    DELETE FROM folders f WHERE f.parent_id IS NOT NULL
        AND NOT EXISTS (SELECT 1 FROM folders p WHERE p.id=f.parent_id);

    RAISE NOTICE '=== CLEANUP COMPLETE ===';
END;
$$;

COMMIT;
